version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SERVER_ADDRESS=:8080

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aviral123
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6389:6379"
